import pandas as pd
from pathlib import Path


# ---------------------------------------------------------
# PATHS
# ---------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
PROCESSED_DIR = BASE_DIR / "data" / "processed"

INPUT_FILE = PROCESSED_DIR / "llm_batch_results.csv"
OUTPUT_FILE = PROCESSED_DIR / "llm_category_comparison.csv"


# ---------------------------------------------------------
# LOAD DATA
# ---------------------------------------------------------

df = pd.read_csv(INPUT_FILE)

# Keep only successfully processed records
df = df[df["processing_status"] == "success"].copy()


# ---------------------------------------------------------
# PREPARE COMPARISON
# ---------------------------------------------------------

comparison_df = df[
    [
        "report_id",
        "category",
        "sub_category",
        "crime_type",
        "severity"
    ]
].copy()


# ---------------------------------------------------------
# IDENTIFY CATEGORY DIFFERENCES
# ---------------------------------------------------------

comparison_df["classification_difference"] = (
    comparison_df["category"].astype(str).str.lower()
    != comparison_df["crime_type"].astype(str).str.lower()
)


# ---------------------------------------------------------
# SUMMARY STATISTICS
# ---------------------------------------------------------

total_records = len(comparison_df)

different_classifications = int(
    comparison_df["classification_difference"].sum()
)

same_classifications = total_records - different_classifications


# ---------------------------------------------------------
# SAVE RESULTS
# ---------------------------------------------------------

comparison_df.to_csv(
    OUTPUT_FILE,
    index=False
)


# ---------------------------------------------------------
# DISPLAY RESULTS
# ---------------------------------------------------------

print("=" * 60)
print("DAY 7 - LLM CATEGORY COMPARISON")
print("=" * 60)

print(f"\nSuccessfully analyzed reports: {total_records}")

print(
    f"LLM interpretation differs from original category: "
    f"{different_classifications}"
)

print(
    f"LLM interpretation is similar to original category: "
    f"{same_classifications}"
)


print("\nClassification Comparison")
print("-" * 60)

for _, row in comparison_df.iterrows():

    print(f"\nReport ID: {row['report_id']}")
    print(f"Original Category: {row['category']}")
    print(f"Original Subcategory: {row['sub_category']}")
    print(f"LLM Crime Type: {row['crime_type']}")
    print(f"Severity: {row['severity']}")
    print(
        f"Classification Difference: "
        f"{'Yes' if row['classification_difference'] else 'No'}"
    )


print("\nAnalytical Note")
print("-" * 60)

print(
    "The comparison illustrates the difference between the "
    "dataset's predefined classification and the semantic "
    "crime interpretation generated by the Large Language Model."
)

print(
    "The LLM crime type should be treated as an interpreted "
    "semantic label and not as a replacement for the original "
    "dataset classification."
)

print(
    "\nImportant: This comparison is based only on the "
    f"{total_records}-report LLM sample and should not be "
    "generalized to the complete dataset."
)


print(f"\nOutput saved to:")
print(OUTPUT_FILE)

print("\n" + "=" * 60)
print("LLM CATEGORY COMPARISON COMPLETE")
print("=" * 60)